# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0012_country_tolauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolasites',
            name='activity_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='agency_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
