mysqldb:
  image: mysql:5.7
  env_file: ./config/mysql.env.secret
nginx:
   image: nginx
   restart: always
   volumes:
      - .:/home/TolaTables
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
   ports:
      - "80:80"
   links:
      - tola
mongodb:
   image: frodenas/mongodb
   env_file: ./config/mongodb.env.secret
   restart: always 
tola:
   build: .
   command: bash -c 'python manage.py migrate && python manage.py loaddata fixtures/tolasites.json && python manage.py loaddata fixtures/sites.json && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
   volumes:
       - .:/code
   expose:
       - "8000"
   links:
       - mysqldb
       - mongodb
