# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silo', '0035_auto_20180404_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommCareCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('form_name', models.CharField(max_length=1000)),
                ('form_id', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
                ('silo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silo.Silo')),
            ],
        ),
    ]
