# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0002_commcarecache_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcarecache',
            name='app_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commcarecache',
            name='app_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
