# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0003_auto_20180406_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='commcarecache',
            name='xmlns_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
