# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0004_commcarecache_xmlns_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commcarecache',
            old_name='xmlns_id',
            new_name='xmlns',
        ),
    ]
