# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0005_auto_20180407_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcarecache',
            name='form_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
