ADMINS:
    - "admin"
    - "tola@tola.org"

ALLOWED_HOSTS:
  - "localhost"
  - "www.mercycorps.org"
  - "www.google.com"
  - "*.github.com"
  - "www.github.com"
  - "api.github.com"
  - "tola-activity-dev.mercycorps.org"
  - "tola-activity-demo.mercycorps.org"
  - "tola-activity.mercycorps.org"
  - "tola-tables.mercycorps.org"
  - "tola-tables-dev.mercycorps.org"
  - "tola-tables-demo.mercycorps.org"
  - "tables.toladata.io"
  - "178.62.204.85"

EMAIL_BACKEND: "django.core.mail.backends.filebased.EmailBackend"

EMAIL_FILE_PATH: "/tmp/tola-messages"

DEV_APPS:
   - 'debug_toolbar'
   - 'report_builder'
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    NAME: "tolatables"
    USER: "dbp"
    PASSWORD: "ttmTolaTabl3s2016"
    HOST: "mysqldb"
    PORT: ""


MONGODB_HOST: "mongodb://mongodb/tola"
MONGODB_NAME: "tola"

GOOGLE_REDIRECT_URL: "https://tables.toladata.io"
GOOGLE_STEP2_URI: "https://tables.toladata.io/gwelcome"
GOOGLE_CLIENT_ID: "445847194486-s6v6mntl2fhn7ve5d0ubolsnvm57l03k.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "vjFMy47999sHMoNd_DZSdmPK"
#GOOGLE_CLIENT_ID: "445847194486-mah10ripofn1bl6q7pgi29ssvfhvq2uu.apps.googleusercontent.com"
#GOOGLE_CLIENT_SECRET: "QXiVgI43yjk9FShCVcVppnmm"


#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "445847194486-mah10ripofn1bl6q7pgi29ssvfhvq2uu.apps.googleusercontent.com"
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "QXiVgI43yjk9FShCVcVppnmm"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "445847194486-s6v6mntl2fhn7ve5d0ubolsnvm57l03k.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "vjFMy47999sHMoNd_DZSdmPK"
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "445847194486-gl2v6ud6ll65vf06vbjaslqqgejad61k.apps.googleusercontent.com"
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "qAAdNMQy77Vwqgj4YgOu20f7"
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS:


TOLA_TABLES_USER: "445847194486-s6v6mntl2fhn7ve5d0ubolsnvm57l03k.apps.googleusercontent.com"
#TOLA_TABLES_USER: "tolaactivity"
TOLA_TABLES_TOKEN: "vjFMy47999sHMoNd_DZSdmPK"
#TOLA_TABLES_TOKEN: "qAAdNMQy77Vwqgj4YgOu20f7"


## ONLY FOR MC ###
# LDAP stuff
LDAP_LOGIN: 'uid=pluma,ou=People,dc=system,dc=mercycorps,dc=org'
LDAP_SERVER: 'ldaps://ldap.mercycorps.org' # ldap prod
LDAP_PASSWORD: 'mc2Plum4pw!' # ldap prod
LDAP_USER_GROUP: 'ertb'
LDAP_ADMIN_GROUP: 'ertb-admin'
#####################


SECRET_KEY: 'r"!0^+)=t*ly6ycprf9@kfw$6fsjd0xoh#pa*2erx1m*lp5k9ko7"'

##### WHEN MC SERVER ADD COSIGN #####
AUTHENTICATION_BACKENDS:
 - 'social.backends.google.GoogleOAuth2'
 - 'django.contrib.auth.backends.ModelBackend'

#### NON_LDAP: False then activate cosign for MC ####
#### OFFLINE_MODE only for raspberry pi ####
# If report server then limit navigation and allow access to public dashboards
REPORT_SERVER: False
OFFLINE_MODE: False
NON_LDAP: True


CACHES:
  default:
    BACKEND: "django.core.cache.backends.locmem.LocMemCache"

TEMPLATE_DEBUG: False
#DEBUG: True
